apiVersion: v1
kind: Service
metadata:
  name: key-value-service
  namespace: key-value
spec:
  type: ClusterIP
  selector:
    app: key-value
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000